/*
  Auto-generated by: https://github.com/pmndrs/gltfjsx
  Command: npx gltfjsx@6.2.16 scene.gltf 
  Author: Lassi Kaukonen (https://sketchfab.com/thesidekick)
  License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
  Source: https://sketchfab.com/3d-models/red-rose-74520e87c3ed46898668c83356dd9cfa
  Title: Red rose
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Rose = (props) => {
  const { nodes, materials } = useGLTF('/Rose/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Red_rose} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Red_rose} />
      </group>
    </group>
  )
}

useGLTF.preload('/Rose/scene.gltf')

export default Rose